# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productbrand_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='productseller',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
