# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180701_0528'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOccasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='occasion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductOccasion'),
        ),
        migrations.AddField(
            model_name='product',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductRooms'),
        ),
        migrations.AddField(
            model_name='product',
            name='style_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductStyles'),
        ),
    ]
