# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180702_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_category', to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='occasion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductOccasion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductRooms'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductStyles'),
        ),
    ]
