# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180706_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSofa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, unique=True)),
                ('seller_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSeller')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='chair_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductChair'),
        ),
        migrations.AddField(
            model_name='product',
            name='designer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductDesigner'),
        ),
        migrations.AddField(
            model_name='product',
            name='sofa_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSofa'),
        ),
        migrations.AddField(
            model_name='product',
            name='table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductTable'),
        ),
    ]
