# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20180712_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arab',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='arab',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productoccasion',
            name='arab',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productrooms',
            name='arab',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='productstyles',
            name='arab',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
