# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummypages',
            name='page_type',
            field=models.CharField(choices=[('about', 'About US'), ('terms', 'Terms'), ('privacy', 'Privacy'), ('faq', 'FAQ'), ('delivery', 'Delivery'), ('exchange', 'Exchange')], default='about', max_length=250),
        ),
    ]
