# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('dbc919a9-0814-4ccc-a789-2f2621d09acc'), max_length=20, null=True),
        ),
    ]
