# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180712_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('75189c57-0dd1-4106-9da7-98af3fa11e78'), max_length=20, null=True),
        ),
    ]
