# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20180719_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('178f5ad3-afe3-40ba-9d61-8c256c32c9a1'), max_length=20, null=True),
        ),
    ]
