# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180719_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('60dbb68f-4585-4ad4-bee5-dd351db1cbd0'), max_length=20, null=True),
        ),
    ]
