# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180719_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('74325310-30b5-4fcc-b51b-7228375a8826'), max_length=20, null=True),
        ),
    ]
