# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180719_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('2ffd9cda-0515-4304-b6de-3e786b4d7327'), max_length=20, null=True),
        ),
    ]
