# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180719_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('09537229-63f6-4a26-9d47-66d6ef514a85'), max_length=20, null=True),
        ),
    ]
