# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20180719_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('c355319f-59f8-493c-94c2-6d58f58bb84c'), max_length=20, null=True),
        ),
    ]
