# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20180719_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('33061c7e-4ecd-4a5d-abe8-b24092033439'), max_length=20, null=True),
        ),
    ]
