# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20180719_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.UUID('2672df7e-dd78-4c21-89fd-5f40f3569f42'), max_length=20, null=True),
        ),
    ]
